In [1]:
### 1. What is NumPy?
# Numpy stands for Numerical Python. It is a Python library used for numerical and scientific computing.
# It provides powerful data structure called an array . 
# It helps to perform mathematical operations on large amount of data.
#Example 
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
### 2. What are the key features of NumPy?
# Multidimensional Arrays support
# Fast numerical operations
# Mathematical functions
# Array indexing and slicing
# Matrix and linear algebra operations
# Memory efficent
#Example 
import numpy as np 
arr = np.array([1,2,3,4,5])
print(arr*2)
print(np.mean(arr))

[ 2  4  6  8 10]
3.0


In [4]:
### 3. Explain the difference between a Python list and a NumPy array.

#Python List :- 
# A list is built in python data structure
# A list can store different data types
# Mathematical operations usually require loops
# Lists are less suitable for large numerical calculations
# List can be created without importing any library

#Numpy Array:- 
# A numpy array is provided by the Numpy library.
# A numpy array generally stores elements of the same data types.
# Mathematical operations can be performed directly on the entire array
# Numpy arrays are efficient for numerical calculations
# Numpy requires importing the Numpy Library


In [8]:
### 4. Indexing and Slicing in NumPy
# Indexing 
# Indexing is used to access a specific elements of a Numpy array.
# Numpy uses zero-based indexing which means the first elements has index 0.
# Examples :-
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr[0])
print(arr[2])

# Slicing 
# Slicing is used to extract a portion of an array.The syntax is :-
# array[start:stop]
# Example :- 
print(arr[1:4])

# For 2D numpy array
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr[1,2])

10
30
[20 30 40]
6


In [9]:
### 5. Calculate base-2, natural, and base-10 logarithms using NumPy.

import numpy as np
arr = np.array([1, 2, 4, 10, 100])
base_2 = np.log2(arr)
natural = np.log(arr)
base_10 = np.log10(arr)

print("Base-2 logarithm:", base_2)
print("Natural logarithm:", natural)
print("Base-10 logarithm:", base_10)




Base-2 logarithm: [0.         1.         2.         3.32192809 6.64385619]
Natural logarithm: [0.         0.69314718 1.38629436 2.30258509 4.60517019]
Base-10 logarithm: [0.         0.30103    0.60205999 1.         2.        ]


In [10]:
### 6. What is the equivalent of enumerate for NumPy arrays?

# The enumerate() function can be used with Numpy arrays to get the index and corresponding values each element.

# Example :-

import numpy as np 
arr = np.array([10,20,30,40,50])

for index, value in enumerate(arr):
    print(index,value)


0 10
1 20
2 30
3 40
4 50


In [12]:
### 7. Write a Python program to create a null vector of size 10 using NumPy.

import numpy as np 
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [14]:
### 8. Find the number of rows and columns of a given matrix using NumPy.
import numpy as np
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

rows , columns = matrix.shape

print("Number of rows: ", rows)
print("Number of columns:", columns)


Number of rows:  3
Number of columns: 3


In [15]:
### 9. Write a Python program to reverse the order of elements in a given NumPy array.
import numpy as np
arr = np.array([1,2,3,4,5])
reverse_arr = arr[::-1]
print("Original array:", arr)
print("Reversed array:", reverse_arr)



Original array: [1 2 3 4 5]
Reversed array: [5 4 3 2 1]


In [18]:
### 10. Create a NumPy array with values ranging from 15 to 30 and calculate the mean
import numpy as np
arr = np.arange(15,31)
mean_value = np.mean(arr)
print("Array:", arr)
print("Mean:" , mean_value)

Array: [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
Mean: 22.5


In [20]:
### 11. Find the square and cube of each element
import numpy as np
arr = np.array([2,4,6,8,10])
square = arr ** 2
cube = arr ** 3
print("Square:", square)
print("Cube:", cube)

Square: [  4  16  36  64 100]
Cube: [   8   64  216  512 1000]


In [21]:
### 12. Find indices of non-zero elements
import numpy as np
arr = np.array([1,2,0,0,4,0])
indices = np.nonzero(arr)
print("Indices of non-zero elements:", indices)



Indices of non-zero elements: (array([0, 1, 4]),)


In [22]:
### 13. Create a 3×3 matrix with values ranging from 0 to 8
import numpy as np
matrix = np.arange(9).reshape(3,3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [25]:
### 14. Create a random vector of size 30 and find the mean value
import numpy as np
vector = np.random.random(30)
mean_value = np.mean(vector)
print(mean_value)

0.3980867787496688


In [26]:
### 15. Create a 3×3 identity matrix using np.eye() and np.identity()
import numpy as np
matrix1 = np.eye(3)
matrix2 = np.identity(3)
print("Using np.eye():")
print(matrix1)
print("Using np.identity():")
print(matrix2)


Using np.eye():
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Using np.identity():
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
### 16. Find common values between two arrays using NumPy
import numpy as np 
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([4,5,6,7,8])
common_values = np.intersect1d(arr1,arr2)
print("Common values:", common_values)


Common values: [4 5]


In [33]:
### 17. Create a random vector of size 10 and sort it in ascending and descending order
import numpy as np
arr = np.random.random(10)
ascending = np.sort(arr)
descending = np.sort(arr)[::-1]
print("Original array:", arr) 
print("Ascending order:", ascending) 
print("Descending order:", descending)


Original array: [0.73451315 0.01630245 0.95129218 0.27421205 0.06656006 0.64659006
 0.25368226 0.52399928 0.38006681 0.73456496]
Ascending order: [0.01630245 0.06656006 0.25368226 0.27421205 0.38006681 0.52399928
 0.64659006 0.73451315 0.73456496 0.95129218]
Descending order: [0.95129218 0.73456496 0.73451315 0.64659006 0.52399928 0.38006681
 0.27421205 0.25368226 0.06656006 0.01630245]


In [1]:
### 18. Consider two random arrays A and B. Write a python prohram to check if they are equal using Numpy?
import numpy as np 
A = np.random.randint(0,10,5)
B = np.random.randint(0,10,5)
print("Array A:" , A)
print("Array B:",  B)

if np.array_equal(A,B):
    print("Arrays are equal.")
else:
    print("Arrays are not equal.")



Array A: [8 9 2 6 4]
Array B: [6 4 8 2 8]
Arrays are not equal.


In [2]:
###19. Create a random vector of size 10 and replace the maximum value by 0 using numpy.
import numpy as np 
arr = np.random.random(10)
print("Original Array :", arr)
max_index = np.argmax(arr)
arr[max_index] = 0
print("Array after replacing maxium value:", arr)

Original Array : [0.10976785 0.74199181 0.15493461 0.05901983 0.56134278 0.41619884
 0.36908869 0.13822578 0.55069536 0.77086876]
Array after replacing maxium value: [0.10976785 0.74199181 0.15493461 0.05901983 0.56134278 0.41619884
 0.36908869 0.13822578 0.55069536 0.        ]


In [1]:
###20. Create a 5×5 matrix with row values ranging from 0 to 4 using NumPy
import numpy as np
matrix = np.tile(np.arange(5), (5,1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [1]:
### 21. Write a Python program to find the memory size of an array using NumPy.
import numpy as np 
arr = np.array([1,2,3,4,5])
memory_size = arr.nbytes

print("Array:", arr)
print("Memory size:", memory_size, "bytes")


Array: [1 2 3 4 5]
Memory size: 40 bytes


In [3]:
### 22. Concatenate two NumPy 2D arrays horizontally
import numpy as np
A = np.array([[1,2],
             [3,4]])
B = np.array([[5,6],
             [7,8]])

result = np.hstack((A,B))
print("Array A:")
print(A)
print("Array B:")
print(B)

print("Horizontally Concatenated array:")

print(result)


Array A:
[[1 2]
 [3 4]]
Array B:
[[5 6]
 [7 8]]
Horizontally Concatenated array:
[[1 2 5 6]
 [3 4 7 8]]


In [4]:
### 23.Write a NumPy program to add, subtract, multiply, and divide arguments element-wise
import numpy as np 

A = np.array([10,20,30,40])
B = np.array([2,4,5,8])

print("Addition:", A+B)
print("Subtraction:", A-B)
print("Multiplication:", A*B)
print("Division:", A/B)

Addition: [12 24 35 48]
Subtraction: [ 8 16 25 32]
Multiplication: [ 20  80 150 320]
Division: [5. 5. 6. 5.]


In [8]:
### 24.Write a Python program to round elements of a NumPy array to the nearest integer
import numpy as np
arr = np.array([1.2,2.7,3.5,4.4,5.9])

round_arr = np.round(arr)

print("Original array :", arr)
print("Rounded array :" , round_arr)

Original array : [1.2 2.7 3.5 4.4 5.9]
Rounded array : [1. 3. 4. 4. 6.]


In [10]:
### 25. Write a Python program to get the floor and ceiling values of the elements of a NumPy array
import numpy as np
arr = np.array([1.2,2.7,3.5,4.4,5.9])

floor_values = np.floor(arr)
ciel_values = np.ceil(arr)

print("Original array :", arr)
print("Floor values :" , floor_values)
print("Celing values :" , ciel_values)


Original array : [1.2 2.7 3.5 4.4 5.9]
Floor values : [1. 2. 3. 4. 5.]
Celing values : [2. 3. 4. 5. 6.]


In [11]:
### 26.Convert angles from degrees to radians using NumPy.
import numpy as np

angles=np.array([0,30,45,90,100])
radians = np.radians(angles)

print("Angles in degrees:", angles)
print("Angles in radians:", radians)

Angles in degrees: [  0  30  45  90 100]
Angles in radians: [0.         0.52359878 0.78539816 1.57079633 1.74532925]


In [15]:
### 27. Create a 10×10 array with random values and find the minimum and maximum values using NumPy
import numpy as np
arr = np.random.random((10,10))
minimum = np.min(arr)
maximum = np.max(arr)
print("Minimum value:", minimum)
print("Maximum value:", maximum)

Minimum value: 0.00030872693605421553
Maximum value: 0.9958086448533653


In [16]:
### 28. Create a 5×5 zero matrix with diagonal elements 1, 2, 3, 4, 5.
import numpy as np
matrix = np.diag([1,2,3,4])
print(matrix)


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [20]:
### 29. Find the dot product of a 5×3 and 3×2 matrix using NumPy.
import numpy as np
matrix1 = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15] ]) 
matrix2 = np.array([ [1, 2], [3, 4], [5, 6] ])
result = np.dot(matrix1,matrix2)
print("Dot product is:")
print(result)

Dot product is:
[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


In [23]:
### 30. Given a 1D array, negate all elements which are between 3 and 8, in place, using NumPy.
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,10])
arr[(arr >= 3) & (arr <= 8)] *= -1
print("Modified array:", arr)

Modified array: [ 1  2 -3 -4 -5 -6 -7 -8 10]


In [25]:
### 31. Extract all numbers between a given range from a NumPy array
import numpy as np
arr = np.array([1,3,5,7,9,11,13,15])
lower = 5
upper = 11
result = arr[(arr >= lower) & (arr <= upper)]
print("Numbers between" , lower, "and", upper, ":", result)

Numbers between 5 and 11 : [ 5  7  9 11]


In [26]:
### 32. Create a 3×3×3 array with random values using NumPy
import numpy as np
arr = np.random.random((3,3,3,))
print(arr)

[[[0.72112228 0.54417105 0.70460858]
  [0.19535019 0.89272711 0.17959106]
  [0.53036215 0.78773197 0.11772453]]

 [[0.1911728  0.95890448 0.14188628]
  [0.84962975 0.54895233 0.55784426]
  [0.72598665 0.7403601  0.6356094 ]]

 [[0.19657679 0.37860352 0.2583068 ]
  [0.08530213 0.41067182 0.99023176]
  [0.51092221 0.77582344 0.92524368]]]


In [29]:
### 33. Compute the determinant, covariance, and inverse of a matrix using NumPy.
import numpy as np
matrix = np.array([
    [1,2],
    [3,4]
])
#Determinant 
determinant = np.linalg.det(matrix)
#Covariance
covariance = np.cov(matrix)
#Inverse
inverse = np.linalg.inv(matrix)

print("Determinant:")
print(determinant)
print("Covariance:")
print(covariance)
print("Inverse:")
print(inverse)


Determinant:
-2.0000000000000004
Covariance:
[[0.5 0.5]
 [0.5 0.5]]
Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [34]:
### 34. Compute the mean, median, mode, standard deviation, and variance of a NumPy array.
import numpy as np
arr = np.array([2,4,4,6,8,10])
#Mean 
mean = np.mean(arr)
#Median
median = np.median(arr)
# Mode
values , counts = np.unique(arr , return_counts=True)
mode = values[np.argmax(counts)]
#Standards deviation
standards_deviation = np.std(arr)
#Variance 
variance = np.var(arr)

print("Mean:", mean) 
print("Median:", median) 
print("Mode:", mode) 
print("Standard Deviation:", standards_deviation) 
print("Variance:", variance)



Mean: 5.666666666666667
Median: 5.0
Mode: 4
Standard Deviation: 2.6874192494328497
Variance: 7.222222222222221


In [36]:
### 35. Convert a 1D array to a 3D array and a 4D array to a 2D array using NumPy.
import numpy as np 
#1D array into 3D array
arr_1d = np.arange(8)
arr_3d = arr_1d.reshape(2,2,2)
print("1D array:")
print(arr_1d)
#4D array into 2D array
arr_4d =  np.arange(16).reshape(2,2,2,2)
arr_2d = arr_4d.reshape(4,4)

print("\n4D array:")
print(arr_4d)

1D array:
[0 1 2 3 4 5 6 7]

4D array:
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [37]:
### 36. Find the eigenvalues and eigenvectors of [[4,1],[2,3]] using Numpy.
import numpy as np
matrix = np.array([
    [4,1],
    [2,3]
])

eigenvalues, eigenvectors = np.linalg.eig(matrix)
np.linalg.eig(matrix)
print("Eigenvalues:")
print(eigenvalues)
print("\n Eigenvectors:")
print(eigenvectors)

Eigenvalues:
[5. 2.]

 Eigenvectors:
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [40]:
### 37. Use np.eye() to create a 4*4 identity matrix and multiply it by another 4*4 random matirx.
import numpy as np
#Create a 4*4 identity matrix
identiy_matrix = np.eye(4)
#Create a 4*4 random matrix 
random_matrix = np.random.random((4,4))
#Multiply the matrices
result = np.dot(identiy_matrix,random_matrix)
print("Identity Matrix:")
print(identiy_matrix)
print("Random 
print("Multiplication Result")
print(result)

Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Multiplication Result
[[0.29335714 0.41337504 0.69940565 0.96595671]
 [0.04491165 0.20411747 0.95707176 0.61352768]
 [0.29027336 0.30247126 0.2900964  0.31446927]
 [0.91411573 0.727285   0.05292831 0.71773095]]


In [43]:
### 38.Find the union and intersection of two arrays using Numpy
#A = [1,2,3,4,5]
#B = [4,5,6,7,8]

import numpy as np
A = np.array([1,2,3,4,5])
B = np.array([4,5,6,7,8])
union = np.union1d(A,B)
intersection = np.intersect1d(A,B)
print("Union")
print(union)
print("Intersection")
print(intersection)

Union
[1 2 3 4 5 6 7 8]
Intersection
[4 5]


In [45]:
### 39. Create two sets from array and demonstrate set difference using Numpy
import numpy as np
A = np.array([1,2,3,4,5])
B = np.array([4,5,6,7,8])
set_A  = set(A)
set_B = set(B)
difference_A_B = np.setdiff1d(set_A, set_B)
difference_B_A = np.setdiff1d(set_B, set_A)

print("Set A:", set_A)
print("Set B:", set_B)

print("Difference (A-B):", difference_A_B)
print("Difference (B-A):", difference_B_A)


Set A: {np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)}
Set B: {np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8)}
Difference (A-B): [{np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)}]
Difference (B-A): [{np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8)}]


In [49]:
### 40. Given p(x) = 4x*2 + 6x -24 , use Numpy to find the roots.
import numpy as np
# Coefficients of 4x*2+6x-24
coefficients = [4, 6, -24]
roots = np.roots(coefficients)
print("Roots:", roots)

Roots: [-3.31173769  1.81173769]
